import 'package:drop_down_list/drop_down_list.dart';

List<SelectedListItem> listOfCountry = [
    SelectedListItem(true, "France - FR"),
    SelectedListItem(false, "Afrique du Sud - ZA"),
    SelectedListItem(false, "Allemagne - DE"),
    SelectedListItem(false, "Andorre - AD"),
    SelectedListItem(false, "Algérie - DZ"),
    SelectedListItem(false, "Angola - AO"),
    SelectedListItem(false, "Anguila - AI"),
    SelectedListItem(false, "Antigua-et-Barbuda - AG"),
    SelectedListItem(false, "Arabie Saoudite - SA"),
    SelectedListItem(false, "Argentine - AR"),
    SelectedListItem(false, "Arménie - AM"),
    SelectedListItem(false, "Aruba - AW"),
    SelectedListItem(false, "Australie - AU"),
    SelectedListItem(false, "Autriche - AT"),
    SelectedListItem(false, "Bahamas - BS"),
    SelectedListItem(false, "Bahreïn - BH"),
    SelectedListItem(false, "Bangladesh - BD"),
    SelectedListItem(false, "Belgique - BE"),
    SelectedListItem(false, "Belize - BZ"),
    SelectedListItem(false, "Bénin - BJ"),
    SelectedListItem(false, "Bermudes - BM"),
    SelectedListItem(false, "Bhoutan - BT"),
    SelectedListItem(false, "Bolovie - BO"),
    SelectedListItem(false, "Bonaire, Saint-Eustache et Saba - BQ"),
    SelectedListItem(false, "Bosnie-Herzégovine - BA"),
    SelectedListItem(false, "Botswana - BW"),
    SelectedListItem(false, "Brésil - BR"),
    SelectedListItem(false, "Brunei - BN"),
    SelectedListItem(false, "Bulgarie - BG"),
    SelectedListItem(false, "Burundi - BI"),
    SelectedListItem(false, "Cameroun - CM"),
    SelectedListItem(false, "Canada - CA"),
    SelectedListItem(false, "Cap-Vert - CV"),
    SelectedListItem(false, "Chine - CN"),
    SelectedListItem(false, "Chili - CL"),
    SelectedListItem(false, "Chypre - CY"),
    SelectedListItem(false, "Colombie - CO"),
    SelectedListItem(false, "Comores - KM"),
    SelectedListItem(false, "Corée du Sud - KR"),
    SelectedListItem(false, "Costa Rica = CR"),
    SelectedListItem(false, "Côte d'ivoire - CI"),
    SelectedListItem(false, "Croatie - HR"),
    SelectedListItem(false, "Curaçao - CW"),
    SelectedListItem(false, "Danemark - DK"),
    SelectedListItem(false, "Djibouti - DJ"),
    SelectedListItem(false, "Dominique - DM"),
    SelectedListItem(false, "Egypte - EG"),
    SelectedListItem(false, "Équateur - EC"),
    SelectedListItem(false, "Espagne - ES"),
    SelectedListItem(false, "Estonie - EE"),
    SelectedListItem(false, "Eswatini - SZ"),
    SelectedListItem(false, "Etats-Unis - US"),
    SelectedListItem(false, "Fidji - FJ"),
    SelectedListItem(false, "Finlande - FI"),
    SelectedListItem(false, "Gabon - GA"),
    SelectedListItem(false, "Gambie - GM"),
    SelectedListItem(false, "Géorgie - GE"),
    SelectedListItem(false, "Ghana - GH"),
    SelectedListItem(false, "Gilbraltar - GI"),
    SelectedListItem(false, "Grèce - GR"),
    SelectedListItem(false, "Grenade - GD"),
    SelectedListItem(false, "Groenland - GL"),
    SelectedListItem(false, "Guadeloupe - GP"),
    SelectedListItem(false, "Guam - GU"),
    SelectedListItem(false, "Guatemala - GT"),
    SelectedListItem(false, "Guernesey - GG"),
    SelectedListItem(false, "Guinée équatoriale - GQ"),
    SelectedListItem(false, "Guinée-Bissau - GW"),
    SelectedListItem(false, "Guyane - GY"),
    SelectedListItem(false, "Guyane française - GF"),
    SelectedListItem(false, "Honduras - HN"),
    SelectedListItem(false, "Hongrie - HU"),
    SelectedListItem(false, "Hong Kong - HK"),
    SelectedListItem(false, "Île Christmas - CX"),
    SelectedListItem(false, "Île de Man - IM"),
    SelectedListItem(false, "Île Norfolk - NF"),
    SelectedListItem(false, "Îles Åland - AX"),
    SelectedListItem(false, "Îles Cocos - CC"),
    SelectedListItem(false, "Îles Cook - CK"),
    SelectedListItem(false, "Îles Falkland - FK"),
    SelectedListItem(false, "Îles Féroé - FO"),
    SelectedListItem(false, "Îles Mariannes du Nord - MP"),
    SelectedListItem(false, "Îles Marshall - MH"),
    SelectedListItem(false, "Îles mineures éloignées des Etats-Unis - UM"),
    SelectedListItem(false, "Îles Salomon - SB"),
    SelectedListItem(false, "Îles Turques-et-Caiques - TC"),
    SelectedListItem(false, "Îles Vierges (américaines) - VI"),
    SelectedListItem(false, "Îles Vierges (britanniques) - VG"),
    SelectedListItem(false, "Inde - IN"),
    SelectedListItem(false, "Indonésie - ID"),
    SelectedListItem(false, "Irlande - IE"),
    SelectedListItem(false, "Islande - IS"),
    SelectedListItem(false, "Israel - IL"),
    SelectedListItem(false, "Italie - IT"),
    SelectedListItem(false, "Japon - JP"),
    SelectedListItem(false, "Jersey - JE"),
    SelectedListItem(false, "Kenya - KE"),
    SelectedListItem(false, "Kirghizistan - KG"),
    SelectedListItem(false, "Kiribati - KI"),
    SelectedListItem(false, "Kosovo - XK"),
    SelectedListItem(false, "Koweït - KW"),
    SelectedListItem(false, "Laos - MO"),
    SelectedListItem(false, "Lesotho - LS"),
    SelectedListItem(false, "Lettonie - LV"),
    SelectedListItem(false, "Liechtenstein - LI"),
    SelectedListItem(false, "Lituanie - LU"),
    SelectedListItem(false, "Luxembourg - LU"),
    SelectedListItem(false, "Macao - MO"),
    SelectedListItem(false, "Macédoine - MK"),
    SelectedListItem(false, "Madagascar - MG"),
    SelectedListItem(false, "Malaisie - MY"),
    SelectedListItem(false, "Maldives - MV"),
    SelectedListItem(false, "Malawi - MW"),
    SelectedListItem(false, "Malte - MT"),
    SelectedListItem(false, "Martinique - MQ"),
    SelectedListItem(false, "Maurice - MU"),
    SelectedListItem(false, "Mauritanie - MR"),
    SelectedListItem(false, "Mayote - YT"),
    SelectedListItem(false, "Mexique - MX"),
    SelectedListItem(false, "Micronésie - FM"),
    SelectedListItem(false, "Moldavie - MD"),
    SelectedListItem(false, "Monaco - MC"),
    SelectedListItem(false, "Mongolie - MN"),
    SelectedListItem(false, "Monténégro - ME"),
    SelectedListItem(false, "Montserrat - MS"),
    SelectedListItem(false, "Mozambique - MZ"),
    SelectedListItem(false, "Namibie - NA"),
    SelectedListItem(false, "Nauru - NR"),
    SelectedListItem(false, "Népal - NP"),
    SelectedListItem(false, "Niger - NE"),
    SelectedListItem(false, "Nigeria - NG"),
    SelectedListItem(false, "Niue - NU"),
    SelectedListItem(false, "Norvège - NO"),
    SelectedListItem(false, "Nouvelle-Calédonie - NC"),
    SelectedListItem(false, "Nouvelle-Zélande - NZ"),
    SelectedListItem(false, "Oman - QA"),
    SelectedListItem(false, "Palau - PW"),
    SelectedListItem(false, "Papouasie-Nouvelle-Guinée - PG"),
    SelectedListItem(false, "Paraguay - PY"),
    SelectedListItem(false, "Pays-Bas - NL"),
    SelectedListItem(false, "Pérou - PE"),
    SelectedListItem(false, "Pitcairn - PN"),
    SelectedListItem(false, "Pologne - PL"),
    SelectedListItem(false, "Polynésie française - PF"),
    SelectedListItem(false, "Portugal - PT"),
    SelectedListItem(false, "Puerto Rico - PR"),
    SelectedListItem(false, "République dominicaine - DO"),
    SelectedListItem(false, "République du Congo - CG"),
    SelectedListItem(false, "République tchèque - CZ"),
    SelectedListItem(false, "Réunion - RE"),
    SelectedListItem(false, "Roumanie - RO"),
    SelectedListItem(false, "Royaume-Uni - GB"),
    SelectedListItem(false, "Rwanda - RW"),
    SelectedListItem(false, "Sahara occidental - EH"),
    SelectedListItem(false, "Saint-Barthémy - BL"),
    SelectedListItem(false, "Saint-Kitts-et-Nevis - KN"),
    SelectedListItem(false, "Saint-Pierre-et-Miquelon - PM"),
    SelectedListItem(false, "Saint-Marin - SM"),
    SelectedListItem(false, "Saint-Martin (néerlandais) - SX"),
    SelectedListItem(false, "Saint-Martin (français) - MF"),
    SelectedListItem(false, "Saint-Siège (Vatican) - VA"),
    SelectedListItem(false, "Saint-Vincent-et-les Grenadines - VC"),
    SelectedListItem(false, "Sainte-Hélène, Ascension et Tristan da Cunha - SH"),
    SelectedListItem(false, "Sainte-Lucie - LC"),
    SelectedListItem(false, "Salvador - SV"),
    SelectedListItem(false, "Samoa - WS"),
    SelectedListItem(false, "Samoa américaines"),
    SelectedListItem(false, "Sao Tomé-et-Principe - ST"),
    SelectedListItem(false, "Serbie - RS"),
    SelectedListItem(false, "Seychelles - SC"),
    SelectedListItem(false, "Sierra Leone - SL"),
    SelectedListItem(false, "Singapour - SG"),
    SelectedListItem(false, "Slovaquie - SK"),
    SelectedListItem(false, "Slovénie - SI"),
    SelectedListItem(false, "Sri Lanka - LK"),
    SelectedListItem(false, "Suède - SE"),
    SelectedListItem(false, "Suisse - CH"),
    SelectedListItem(false, "Suriname - SR"),
    SelectedListItem(false, "Svalbard et Jan Mayen - SJ"),
    SelectedListItem(false, "Taiwan - TW"),
    SelectedListItem(false, "Tanzanie - TZ"),
    SelectedListItem(false, "Tchad - TD"),
    SelectedListItem(false, "Territoire britannique de l'océan Indien - IO"),
    SelectedListItem(false, "Thaïlande - TH"),
    SelectedListItem(false, "Timor-Leste -TL"),
    SelectedListItem(false, "Togo - TG"),
    SelectedListItem(false, "Tokelo - TK"),
    SelectedListItem(false, "Tonga - TO"),
    SelectedListItem(false, "Tunisie - TN"),
    SelectedListItem(false, "Tuvalu - TV"),
    SelectedListItem(false, "Uruguay - UY"),
    SelectedListItem(false, "Vietnam - VN"),
    SelectedListItem(false, "Wallis-et-Futuna - WF"),
    SelectedListItem(false, "Zambie - ZM"),
  ];
  